name: Test Matrix

on: [push]

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, brown]
        include:
        - color: white
          pet: tiger
        - color: brown
          pet: dog
    steps:
    - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}"
  
  
